### ISSUE TITLE
博主为什么维护这么奇怪的项目？

### ISSUE THREAD

**Issue by Mulf** [iamswain25/political-life#1]
今天闲来无事在网上乱逛，莫名其妙的的进入了这个repo，看了几篇感觉还蛮有意思，但是谈不上多少有意思的内容（毕竟只是日记）。不知道博主为什么要把这本书做成一个网页还翻译成各种语言？果然世界这么大，什么样奇怪的人都有啊

**Comment by iamswain25** [comment]
@Mulf 书已绝版了，不能正常翻译出版。你去问问王沪宁为什么将它绝版。

**Comment by Mulf** [comment]
书绝版很正常，但你为什么要把他放到网上呢?感觉维护这个还是要耗不少精力的啊

**Comment by iamswain25** [comment]
@Mulf 初次做好以后，维护不耗精力。github免费，我就闲时间没事翻译翻译。

**Comment by zFitness** [comment]
牛逼了

**Comment by zFitness** [comment]
这个书讲了啥？

**Comment by iamswain25** [comment]
讲了当代上海人的精神境界
